update travis file for numerical-core

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,40 +1,53 @@
-language: haskell
+language: haskell 
+# NB: don't set `language: haskell` here
 
+# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
 env:
-  matrix:
-    # - HPVER=2012.4.0.0
-    # - HPVER=2013.2.0.0
-    # - GHCVER=7.0.4
-    # - GHCVER=7.2.2
-    - GHCVER=7.6.3
-    - GHCVER=7.8.1
-    - GHCVER=head
-  global:
-    - CABALVER=1.18
-    - UBUNTU_PKGS=""
-    - EXTRA_DEPS_PRE=""
-    - HEAD_DEPS=""
-    - EXTRA_DEPS=""
-    - CABAL_FLAGS=""
+ # - GHCVER=7.4.2
+ - GHCVER=7.6.3
+ - GHCVER=7.8.1
+ - GHCVER=head
 
 matrix:
   allow_failures:
-    - env: GHCVER=head
-    - env: GHCVER=7.6.3
+   - env: GHCVER=head
 
+
+
+# Note: the distinction between `before_install` and `install` is not important.
 before_install:
-  - sudo apt-get update 
-  # - sudo apt-get install gfortran
-  - git clone http://github.com/wellposed/wellposed-travis travis
-  # - sudo apt-get install libblas-dev liblapack-dev
-  # - ./travis/scripts/build-openblas.sh
-  - source travis/scripts/set_env.sh
-  # - export CABAL_FLAGS="-f-OpenBlas"
-  - ./travis/scripts/before_install.sh
+ - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+ - travis_retry sudo apt-get update
+ - travis_retry sudo apt-get install libblas-dev liblapack-dev
+ - travis_retry sudo apt-get install cabal-install-1.18 ghc-$GHCVER-prof ghc-$GHCVER-dyn happy
+ - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 
-install: ./travis/scripts/install.sh
+install:
+ - sudo /opt/ghc/$GHCVER/bin/ghc-pkg recache
+ - /opt/ghc/$GHCVER/bin/ghc-pkg recache --user
+ - cabal-1.18 update
+ - cabal-1.18 install --only-dependencies --enable-tests --enable-benchmarks
 
-script: ./travis/scripts/script.sh
+# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
+script:
+ - cabal-1.18 configure --enable-tests --enable-benchmarks -v2  # -v2 provides useful information for debugging
+ - cabal-1.18 build   # this builds all libraries and executables (including tests/benchmarks)
+ - cabal-1.18 test  --show-details=always
+ - cabal-1.18 check
+ - cabal-1.18 sdist   # tests that a source-distribution can be generated
+
+# The following scriptlet checks that the resulting source distribution can be built & installed
+ - function install_from_tarball {
+   export SRC_TGZ=$(cabal-1.18 info . | awk '{print $2 ".tar.gz";exit}') ;
+   if [ -f "dist/$SRC_TGZ" ]; then
+      cabal-1.18 install "dist/$SRC_TGZ";
+   else
+      echo "expected 'dist/$SRC_TGZ' not found";
+      exit 1;
+   fi
+   }
+ - install_from_tarball
+
 
 notifications:
   email: false
